sudo: false

language: nix
nix: 2.0.4

# Caching so the next build will be fast too.
cache:
  directories:
  - /nix

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

jobs:
  include:
    - name: "GHC 8.6.5"
      env: GHC=ghc865
    - name: "GHC 8.8.3"
      env: GHC=ghc883
script:
  - nix-build --argstr compiler $GHC
